### PR TITLE
Retrieve more statistics from network & assembler threads and ring buffers

### PR DESCRIPTION
**Pull request by dstndstn**
- when retrieving assembled_chunks from the ring buffer, return a bitmask of where in the ringbuffer the chunks were found (what level, etc)
- add debugging ability to inject chunks
- track time used in network & assembler threads
- use std::thread for network & assembler threads

### CODE REVIEW

**Comment by dstndstn** [comment]
This breaks ch_frb_l1 master

**Comment by kmsmith137** [comment]
Oh wow, this looks fantastic, but I suspect there will be conflicts with the 'v5_devel' branch, where I was implementing some changes needed for the "master" L1 process.  I didn't know you were making low-level changes on another branch!

Let's try to merge the webapp and v5_devel branches, and name the result "ch_frb_io v5".  Looks like we both followed good git practices of committing in small incremental units, so (assuming we do get conflicts) then merging one branch to the other "a few commits at a time" should minimize pain and suffering

I'm spread thin so probably can't get to this before the f2f meeting, any chance I can turn this over to you?  :)

**Comment by dstndstn** [comment]
Builds with https://github.com/kmsmith137/ch_frb_l1/pull/6

**Comment by dstndstn** [comment]
This has been on the back-burner for a while, which always leads to trouble :)

@kmsmith137 sure thing, I'll merge this with v5_devel.

**Comment by kmsmith137** [comment]
Continuing the previous comment...

One case where we'll definitely get a conflict is your commit (I'm a big fan of this change, thanks for making it!)

  "use std::thread instead of pthread" 

and my commit 

   "change semantics of intensity_network_stream::join_threads() so that multiple concurrent calls are allowed"

which slightly changes the stream state model and rearranges some pthread_* calls.  So we'll get some nontrivial conflicts for sure...

**Comment by kmsmith137** [comment]
OK thanks!  Let me know if it would useful to chat about any of the changes on v5_devel.  I think the git commit messages do a reasonable job of stating what changes were made, but the motivation behind making them isn't necessarily clear!

**Comment by dstndstn** [comment]
The merge went pretty smoothly!

**Pull request merged**
